language: ruby
cache: bundler
rvm:
  - 2.2.1
git:
  submodules: false
env:
  global:
    - ADMIN_PWD=testenv
    - RACK_ENV=test
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
addons:
  #code_climate:
  #  repo_token: b0281ad9d663105f20247984ed886f4434a3302657ee22791d9de51d9a3df895
  apt:
    packages:
install:
  - bundle install
before_script:
  - ./scripts/beforescript.sh
script:
  - ./scripts/builddata.sh
  - rake test --trace
  - ./scripts/gendocs.sh
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: princetonridgeha-staging
  skip_cleanup: true
  run: "rake db:migrate"
