language: ruby
cache: bundler
rvm:
  - 2.2.1
git:
  submodules: false
env:
  global:
    - CODACY_PROJECT_TOKEN=5f064f16d2a448959ea7b2565f9006d9
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
addons:
  #code_climate:
  #  repo_token: b0281ad9d663105f20247984ed886f4434a3302657ee22791d9de51d9a3df895
  apt:
    packages:
install:
  - bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - echo 'Configuring JIT variables...'
  - sed 's/TRAVISCOMMIT/'$TRAVIS_COMMIT'/' ./frontend/builddata.partial.rb > ./frontend/builddata.partial2.rb
  - sed 's/TRAVISBUILD/'$TRAVIS_BUILD_NUMBER'/' ./frontend/builddata.partial2.rb > ./frontend/inc/builddata.rb
  #- head ./inc/builddata.rb
  - rake test --trace
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: princetonridgeha
  skip_cleanup: true
  run: "rake db:migrate"
